services:
  everactive:
    build:
      context: ..
      dockerfile: package.Dockerfile
    volumes: [ ./application.yml:/app/application.yml ]
    links: [ db ]
    ports: [ "8088:8080" ]

  db:
    image: postgres:18-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: everactive_dev
    ports: [ "5432:5432" ]
